from app.vector_store import VectorStore
from app.generate_query_variations import expand_queries, parallel_search
from diskcache import Cache

rag_cache = Cache("./cache")#Cache for RAG results, mapping query to retrieved context and sources. This can help speed up responses for repeated queries by avoiding redundant retrievals from the vector store.

class RAG:
    def __init__(self, store: VectorStore):
        self.store = store

    async def search(self, query):
        if query in rag_cache:
            return rag_cache[query]
        
        queries = expand_queries(query)  # Generate variations of the query to improve retrieval recall by capturing different phrasings and keywords that might be present in the documents. This can help retrieve more relevant chunks from the vector store, which can then be re-ranked for better context for the LLM.

        all_results_list = await parallel_search(self.store, queries)  # Perform parallel searches for all query variations to efficiently retrieve a larger pool of candidate chunks from the vector store. This allows us to leverage the different phrasings and keywords generated by expand_queries to maximize recall and get a richer set of relevant chunks for the LLM to use as context.

        # Deduplicate results
        seen = set()
        unique_results = []

        for r in all_results_list:
            key = (r["source"], r["content"])
            if key not in seen:
                seen.add(key)
                unique_results.append(r)

        # Take top-k (after merging)
        top_results = unique_results[:3]  # Take the top 3 results after deduplication to use as context for the LLM. This helps ensure that we provide the most relevant and diverse information to the LLM while keeping the context concise and focused.
        
        # 2. Extract content
        context = "\n".join([r["content"] for r in top_results])

        # 3. Extract sources
        sources = list(set([r["source"] for r in top_results]))

        rag_cache[query] = {"context": context, "sources": sources}  # Cache the result

        return {
            "context": context,
            "sources": sources
        }
